/* eslint-disable no-console */
/**
 * Catalog completeness audit — for every release, report which optional
 * fields are missing so we can prioritize what to fill next.
 *
 * Categories:
 *   · NO COVER       — release has no cover image asset
 *   · NO DSP         — no streaming/bandcamp links at all
 *   · NO STORY       — empty `notes` (no liner-note body text)
 *   · NO ART CREDITS — no cover-art / photography / design credit
 *   · NO TRACKLIST   — empty tracklist (could be a single, but flag anyway)
 *   · NO PRESS       — no pressQuote docs reference this release
 *
 * Output: a sectioned table written to docs/catalog-gaps.md so you can
 * skim it as a punch list. Also prints a summary to stdout.
 *
 * Run: npx tsx scripts/audit-catalog-gaps.ts
 */
import { createClient } from "@sanity/client";
import { config } from "dotenv";
import { resolve } from "node:path";
import { writeFileSync } from "node:fs";

config({ path: resolve(process.cwd(), ".env.local") });

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production",
  apiVersion: "2025-01-01",
  token: process.env.SANITY_API_WRITE_TOKEN!,
  useCdn: false,
});

type Release = {
  _id: string;
  title: string;
  slug: string;
  year?: number;
  catalogNumber?: string;
  label?: string;
  artistNames?: string[];
  hasCover: boolean;
  hasDsp: boolean;
  hasNotes: boolean;
  hasArtCredits: boolean;
  hasTracklist: boolean;
  pressCount: number;
  withdrawn?: boolean;
};

async function main() {
  const releases: Release[] = await client.fetch(`
    *[_type == "release"] | order(coalesce(year, 9999) desc, title asc) {
      _id, title, "slug": slug.current, year, catalogNumber, label,
      withdrawn,
      "artistNames": artists[]->name,
      "hasCover": defined(cover),
      "hasDsp": defined(bandcampUrl) || defined(spotifyUrl) || defined(appleMusicUrl) || defined(youtubeUrl) || defined(soundcloudUrl),
      "hasNotes": defined(notes) && length(pt::text(notes)) > 0,
      "hasArtCredits": count(credits[role in ["Cover art", "Photography", "Art direction", "Layout / design", "Design"]]) > 0,
      "hasTracklist": count(tracklist) > 0,
      "pressCount": count(*[_type == "pressQuote" && relatedRelease._ref == ^._id])
    }
  `);

  // Filter out withdrawn — we don't care about gaps on records we're not
  // surfacing publicly.
  const active = releases.filter((r) => !r.withdrawn);

  const stats = {
    total: active.length,
    noCover: active.filter((r) => !r.hasCover).length,
    noDsp: active.filter((r) => !r.hasDsp).length,
    noNotes: active.filter((r) => !r.hasNotes).length,
    noArtCredits: active.filter((r) => !r.hasArtCredits).length,
    noTracklist: active.filter((r) => !r.hasTracklist).length,
    noPress: active.filter((r) => r.pressCount === 0).length,
  };

  console.log(`\n— ${active.length} active releases —`);
  console.log(`  ${stats.noCover.toString().padStart(3)} missing cover`);
  console.log(`  ${stats.noDsp.toString().padStart(3)} missing all DSP links`);
  console.log(`  ${stats.noNotes.toString().padStart(3)} missing liner notes (story text)`);
  console.log(`  ${stats.noArtCredits.toString().padStart(3)} missing cover-art credits`);
  console.log(`  ${stats.noTracklist.toString().padStart(3)} missing tracklist`);
  console.log(`  ${stats.noPress.toString().padStart(3)} have zero linked press`);

  // ── markdown report ──────────────────────────────────────────────────────
  const lines: string[] = [];
  lines.push("# Catalog gaps");
  lines.push("");
  lines.push(`Auto-generated by \`scripts/audit-catalog-gaps.ts\`. Last run: ${new Date().toISOString().slice(0, 10)}.`);
  lines.push("");
  lines.push(`**${active.length} active releases.** This file lists every gap so you can fill them in priority order.`);
  lines.push("");

  const sections: { title: string; pred: (r: Release) => boolean }[] = [
    { title: "Missing cover art", pred: (r) => !r.hasCover },
    { title: "Missing all DSP / streaming links", pred: (r) => !r.hasDsp },
    { title: "Missing liner notes (story text)", pred: (r) => !r.hasNotes },
    { title: "Missing cover-art credits", pred: (r) => !r.hasArtCredits },
    { title: "Missing tracklist", pred: (r) => !r.hasTracklist },
    { title: "Zero press pieces", pred: (r) => r.pressCount === 0 },
  ];

  for (const sec of sections) {
    const rows = active.filter(sec.pred);
    lines.push(`## ${sec.title} — ${rows.length}`);
    lines.push("");
    if (rows.length === 0) {
      lines.push("_None — all good._");
      lines.push("");
      continue;
    }
    lines.push("| Year | Cat # | Title | Artists | Studio link |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const r of rows) {
      const artists = (r.artistNames ?? []).join(", ");
      const studio = `[edit](https://thespacepit.sanity.studio/structure/release;${r._id})`;
      lines.push(
        `| ${r.year ?? "—"} | ${r.catalogNumber ?? "—"} | **${r.title}** | ${artists} | ${studio} |`,
      );
    }
    lines.push("");
  }

  writeFileSync(resolve("docs", "catalog-gaps.md"), lines.join("\n"));
  console.log(`\n→ wrote docs/catalog-gaps.md (${lines.length} lines)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
