/* eslint-disable no-console */
/**
 * Sanity orphan-doc audit — surface docs that aren't connected to anything
 * so we can either link or delete them.
 *
 * Categories:
 *   · Artists with zero releases AND zero credits AND zero crew flag
 *     → strong candidates for deletion or relabeling as stub-only
 *   · Press with no relatedRelease + no relatedEra + no relatedArtist
 *     + no relatedBrand
 *     → these are floating quotes that only surface on the global press wall
 *   · Releases with zero artists referenced
 *   · Sessions with no people, no releases
 *   · Brands with no releases AND no press AND no artists
 *
 * Output: docs/orphan-audit.md + stdout summary.
 *
 * Run: npx tsx scripts/audit-orphan-docs.ts
 */
import { createClient } from "@sanity/client";
import { config } from "dotenv";
import { resolve } from "node:path";
import { writeFileSync } from "node:fs";

config({ path: resolve(process.cwd(), ".env.local") });

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production",
  apiVersion: "2025-01-01",
  token: process.env.SANITY_API_WRITE_TOKEN!,
  useCdn: false,
});

async function main() {
  const [
    orphanArtists,
    orphanPress,
    releasesNoArtists,
    sessionsEmpty,
    brandsEmpty,
  ]: [
    Array<{ _id: string; name: string; slug: string }>,
    Array<{ _id: string; outlet?: string; headline?: string; year?: number }>,
    Array<{ _id: string; title: string }>,
    Array<{ _id: string; title: string; date?: string }>,
    Array<{ _id: string; name: string }>,
  ] = await Promise.all([
    client.fetch(`
      *[_type == "artist"
        && count(*[_type == "release" && references(^._id)]) == 0
        && count(*[_type == "release" && ^._id in credits[].person._ref]) == 0
        && tspCrew != true
        && onLabel != true
      ]{ _id, name, "slug": slug.current }
    `),
    client.fetch(`
      *[_type == "pressQuote"
        && !defined(relatedRelease)
        && !defined(relatedEra)
        && !defined(relatedArtist)
        && !defined(relatedBrand)
      ]{ _id, outlet, headline, year }
    `),
    client.fetch(`
      *[_type == "release" && count(artists) == 0]{ _id, title }
    `),
    client.fetch(`
      *[_type == "studioSession" && count(people) == 0 && count(releases) == 0]{
        _id, title, date
      }
    `),
    client.fetch(`
      *[_type == "brand"
        && count(*[_type == "release" && references(^._id)]) == 0
        && count(*[_type == "pressQuote" && (relatedBrand._ref == ^._id || lower(outlet) == lower(^.name))]) == 0
        && count(*[_type == "artist" && references(^._id)]) == 0
      ]{ _id, name }
    `),
  ]);

  const lines: string[] = [];
  lines.push("# Orphan / floating Sanity docs");
  lines.push("");
  lines.push(
    `Auto-generated by \`scripts/audit-orphan-docs.ts\`. Last run: ${new Date().toISOString().slice(0, 10)}.`,
  );
  lines.push("");
  lines.push(
    "These docs exist in Sanity but aren't connected to anything that surfaces them on the public site. Each is a candidate for either (a) link to the right thing, or (b) delete.",
  );
  lines.push("");

  function section<T extends { _id: string }>(
    title: string,
    rows: T[],
    fmt: (r: T) => string,
  ) {
    lines.push(`## ${title} — ${rows.length}`);
    lines.push("");
    if (rows.length === 0) {
      lines.push("_None — clean._");
      lines.push("");
      return;
    }
    for (const r of rows) {
      lines.push(`- ${fmt(r)}`);
    }
    lines.push("");
  }

  section(
    "Artists with zero releases AND zero credits AND not in crew",
    orphanArtists,
    (a) =>
      `**${a.name}** — slug \`${a.slug}\` — [edit](https://thespacepit.sanity.studio/structure/artist;${a._id})`,
  );

  section(
    "Press pieces with no related release / era / artist / brand",
    orphanPress,
    (p) =>
      `${p.year ?? "?"} · *${p.outlet ?? "—"}* · ${p.headline ?? "(no headline)"} — [edit](https://thespacepit.sanity.studio/structure/pressQuote;${p._id})`,
  );

  section(
    "Releases with zero artist references",
    releasesNoArtists,
    (r) =>
      `**${r.title}** — [edit](https://thespacepit.sanity.studio/structure/release;${r._id})`,
  );

  section(
    "Sessions with no people AND no releases",
    sessionsEmpty,
    (s) =>
      `${s.date ?? "—"} · **${s.title}** — [edit](https://thespacepit.sanity.studio/structure/studioSession;${s._id})`,
  );

  section(
    "Brands with no releases / press / artists pointing at them",
    brandsEmpty,
    (b) =>
      `**${b.name}** — [edit](https://thespacepit.sanity.studio/structure/brand;${b._id})`,
  );

  writeFileSync(resolve("docs", "orphan-audit.md"), lines.join("\n"));

  console.log(`\n— Orphan audit —`);
  console.log(`  ${orphanArtists.length.toString().padStart(4)} orphan artists`);
  console.log(`  ${orphanPress.length.toString().padStart(4)} unrelated press pieces`);
  console.log(`  ${releasesNoArtists.length.toString().padStart(4)} releases with no artist ref`);
  console.log(`  ${sessionsEmpty.length.toString().padStart(4)} empty sessions`);
  console.log(`  ${brandsEmpty.length.toString().padStart(4)} unconnected brands`);
  console.log(`\n→ wrote docs/orphan-audit.md`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
