/**
 * Geocode every unique tour city from app/_lib/shows.ts via OpenStreetMap
 * Nominatim. Writes app/_lib/city-coords.ts with a static lookup map.
 *
 * Rate-limited to 1 req/sec per Nominatim usage policy. ~3 min for 160 cities.
 *
 * Run:  npx tsx scripts/geocode-tour-cities.ts
 *
 * Re-run safely — preserves any existing entries you've hand-corrected by
 * marking them as "hand-tuned".
 */

import { SHOWS } from "../app/_lib/shows";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";

const OUTPUT = resolve(process.cwd(), "app/_lib/city-coords.ts");

type Coord = { lat: number; lng: number; country?: string; handTuned?: boolean };

// Cities we KNOW don't geocode well or are placeholder strings — skip.
const SKIP = new Set([
  "Multiple UK cities",
  "Multiple US cities",
  "Chicago/LA",
  "Indiana", // ambiguous, no city
]);

// Cities Nominatim disambiguates badly — pre-seed with the right answer.
const HINTS: Record<string, string> = {
  "New York": "New York City, NY, USA",
  "Brooklyn": "Brooklyn, New York, USA",
  "Manhattan": "Manhattan, New York, USA",
  "Queens": "Queens, New York, USA",
  "Bronx": "Bronx, New York, USA",
  "Newcastle": "Newcastle upon Tyne, UK",
  "Newcastle Upon Tyne": "Newcastle upon Tyne, UK",
  "Washington": "Washington DC, USA",
  "Portland": "Portland, Oregon, USA",
  "Cambridge": "Cambridge, Massachusetts, USA",
  "Springfield": "Springfield, Missouri, USA",
  "Columbus": "Columbus, Ohio, USA",
  "Salem": "Salem, Oregon, USA",
  "Berlin": "Berlin, Germany",
  "Paris": "Paris, France",
  "London": "London, UK",
  "Dublin": "Dublin, Ireland",
  "Bristol": "Bristol, UK",
  "Manchester": "Manchester, UK",
  "Birmingham": "Birmingham, UK",
  "Cardiff": "Cardiff, Wales, UK",
  "Glasgow": "Glasgow, Scotland, UK",
  "Edinburgh": "Edinburgh, Scotland, UK",
  "Belfast": "Belfast, Northern Ireland, UK",
  "Aberdeen": "Aberdeen, Scotland, UK",
};

function uniqueCities(): string[] {
  const seen = new Set<string>();
  for (const s of SHOWS) {
    if (!s.city) continue;
    const k = s.city.trim();
    if (!k || SKIP.has(k)) continue;
    seen.add(k);
  }
  return [...seen].sort();
}

async function geocode(city: string): Promise<Coord | null> {
  const query = HINTS[city] ?? city;
  const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query)}&format=json&limit=1`;
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "spacepit-web/1.0 (https://thespacepit.com)" },
    });
    if (!res.ok) return null;
    const data = (await res.json()) as Array<{ lat: string; lon: string; display_name?: string }>;
    if (data.length === 0) return null;
    const top = data[0];
    const countryMatch = top.display_name?.split(",").pop()?.trim();
    return {
      lat: parseFloat(top.lat),
      lng: parseFloat(top.lon),
      country: countryMatch,
    };
  } catch (err) {
    console.warn(`  ⚠ ${city}: ${(err as Error).message}`);
    return null;
  }
}

function readExisting(): Map<string, Coord> {
  if (!existsSync(OUTPUT)) return new Map();
  const text = readFileSync(OUTPUT, "utf-8");
  const m = text.match(/export const CITY_COORDS[^=]*=\s*(\{[\s\S]*?\});/);
  if (!m) return new Map();
  try {
    // Eval-ish — file is generated code, safe to JSON parse after a tweak.
    const json = m[1]
      .replace(/(\w+):/g, '"$1":')
      .replace(/'/g, '"');
    const obj = JSON.parse(json) as Record<string, Coord>;
    return new Map(Object.entries(obj));
  } catch {
    return new Map();
  }
}

function writeOutput(map: Map<string, Coord>) {
  const sorted = [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  const lines = sorted.map(([k, v]) => {
    const parts: string[] = [`lat: ${v.lat}`, `lng: ${v.lng}`];
    if (v.country) parts.push(`country: ${JSON.stringify(v.country)}`);
    if (v.handTuned) parts.push(`handTuned: true`);
    return `  ${JSON.stringify(k)}: { ${parts.join(", ")} },`;
  });
  const text = `// Auto-generated by scripts/geocode-tour-cities.ts
// City → lat/lng for tour pin rendering. Source: OpenStreetMap Nominatim,
// with disambiguation hints inside the geocoder. Hand-correct an entry by
// setting handTuned: true and the geocoder will skip it on re-run.

export type CityCoord = { lat: number; lng: number; country?: string; handTuned?: boolean };

export const CITY_COORDS: Record<string, CityCoord> = {
${lines.join("\n")}
};
`;
  writeFileSync(OUTPUT, text);
}

async function main() {
  const cities = uniqueCities();
  const existing = readExisting();
  const todo = cities.filter((c) => !existing.has(c) || !existing.get(c)?.handTuned);

  console.log(`📍 ${cities.length} unique cities total. ${todo.length} to geocode.`);
  if (todo.length === 0) {
    console.log("Nothing to do.");
    return;
  }

  const out = new Map(existing);
  let ok = 0;
  for (const c of todo) {
    process.stdout.write(`  ${c.padEnd(34, " ").slice(0, 34)} `);
    const coord = await geocode(c);
    if (coord) {
      out.set(c, coord);
      console.log(`✓ ${coord.lat.toFixed(2)}, ${coord.lng.toFixed(2)}  · ${coord.country ?? "?"}`);
      ok += 1;
    } else {
      console.log("✗ no match");
    }
    // Nominatim policy: ≤1 req/sec
    await new Promise((res) => setTimeout(res, 1100));
  }

  writeOutput(out);
  console.log(`\n✅ ${ok}/${todo.length} geocoded. Total entries: ${out.size}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
