import { release } from "./release";
import { artist } from "./artist";
import { pressQuote } from "./pressQuote";
import { liveDate } from "./liveDate";
import { studioSession } from "./studioSession";
import { show } from "./show";
import { mix } from "./mix";
import { project } from "./project";
import { brand } from "./brand";
import { studio } from "./studio";
import { place } from "./place";
import { gear } from "./gear";
import { pack } from "./pack";
import { video } from "./video";
import { photo } from "./photo";
import { flyer } from "./flyer";
import { vaultDrop } from "./vaultDrop";
import { highlight } from "./highlight";
import { subscriber } from "./subscriber";

export const schemaTypes = [release, artist, pressQuote, liveDate, studioSession, show, mix, project, brand, studio, place, gear, pack, video, photo, flyer, vaultDrop, highlight, subscriber];
