// Filtered to ONLY artists who actually recorded at thespacepit
// (Brooklyn or Medellín). Source: TSP_Sessions_v8_GLOBAL.xlsx, filtered by
// "Location / Studio" containing "Space Pit" or "TSP", then hand-cleaned per
// Nick's notes (no LA-only collaborators, no Colombia-only collaborators).
//
// Edit by hand: add new names alphabetically, remove if needed.

export const STUDIO_CLIENTS: string[] = [
  "50 Backwoods",
  "A$AP Ferg",
  "A-Trak",
  "Action Bronson",
  "Baauer",
  "Big Boi",
  "Cadence Weapon",
  "Chino Amobi",
  "Cleo Reed",
  "Clockwork Crosby",
  "Conductor Williams",
  "Daniel Aged",
  "Danny Brown",
  "Dev Hynes (Blood Orange)",
  "DJ Earl",
  "Drop The Lime",
  "Duendita",
  "El-P",
  "Elliot Lipp",
  "Faker",
  "Father",
  "Fatboi Shariff",
  "Flatbush Zombies",
  "Flying Lotus",
  "Gangsta Boo",
  "Gareth Jones",
  "Haai",
  "Haleek Maul",
  "Hudson Mohawke",
  "Ian Isiah",
  "Jesse Boykins",
  "Junglepussy",
  "Just Blaze",
  "Kaytranada",
  "Kelela",
  "Kid Kreep",
  "Kilo Kish",
  "Killer Mike",
  "KOAD x Kindness",
  "L-Vis 1990",
  "Lao",
  "Lauren Flax",
  "Men Women & Children",
  "Michael Christmas",
  "Mikey Petralia",
  "Mykki Blanco",
  "NguzuNguzu",
  "Nick Catchdubs",
  "Ns-Dos",
  "Oak City Slums",
  "Phil Chang",
  "Prefuse 73",
  "Quazzy",
  "Remy Banks",
  "Robyn",
  "Run the Jewels",
  "Rush Davis",
  "Russell E.L. Butler",
  "Shash'U",
  "Sinjin Hawke",
  "Sinister Dane",
  "Sizarr",
  "Skepta",
  "Spiritual Friendship",
  "Superhero Killer",
  "Taso",
  "The Martinez Brothers",
  "Tribe Icky",
  "Vin Sol & Matrixxman",
];
