// Source of truth: Drive THESPACEPIT CLIENT LIST (Sep 2025) +
// hand-curated list from earlier sessions. Merged + alphabetized.
// Edit by hand to add/remove; canonical spellings preferred.

export const STUDIO_CLIENTS: string[] = [
  "21 Savage",
  "24hrs",
  "50 Backwoods",
  "A$AP 12vy",
  "A$AP Ferg",
  "A$AP Nasty",
  "Action Bronson",
  "Akai Solo",
  "Alex Tumay",
  "A-Trak",
  "Azealia Banks",
  "Baauer",
  "B.I.C.",
  "Big Boi",
  "Black Noise",
  "Byron The Aquarius",
  "Cadence Weapon",
  "Chino Amobi",
  "Cleo Reed",
  "Clockwork Crosby",
  "Conductor Williams",
  "Conway The Machine",
  "D Double E",
  "Daniel Aged",
  "Danny Brown",
  "Dave 1",
  "Dev Hynes (Blood Orange)",
  "DJ Earl",
  "Dre Skull",
  "Drop The Lime",
  "Duendita",
  "Elliot Lipp",
  "El-P",
  "Faker",
  "Fatboi Shariff",
  "Father",
  "Flatbush Zombies",
  "Flying Lotus",
  "Gangsta Boo",
  "Gareth Jones",
  "Haai",
  "Haleek Maul",
  "Hersh Singh",
  "Hudson Mohawke",
  "Ian Isiah",
  "Jacques Greene",
  "Jesse Boykins",
  "Jesse Marco",
  "Joe LaPorta",
  "Joey Raia",
  "Junglepussy",
  "Just Blaze",
  "Kaytranada",
  "KeiyaA",
  "Kelela",
  "Kid Kreep",
  "Killer Mike",
  "Kilo Kish",
  "Kitty Cash",
  "KOAD x Kindness",
  "Lao",
  "Laraaji",
  "Lauren Flax",
  "Leon Kelly",
  "L-Vis 1990",
  "Machinedrum",
  "Makonnen",
  "Men Women & Children",
  "Meyhem Lauren",
  "Michael Christmas",
  "Michna",
  "Mikey Petralia",
  "Mykki Blanco",
  "NguzuNguzu",
  "Nick Catchdubs",
  "Novelist",
  "Ns-Dos",
  "Oak City Slums",
  "Phil Chang",
  "Prefuse 73",
  "Prodigy",
  "Quazzy",
  "Raekwon",
  "Remy Banks",
  "Robyn",
  "Roc Marciano",
  "Rome Streetz",
  "Run the Jewels",
  "Rush Davis",
  "Russell E.L. Butler",
  "Salva",
  "Sammy Bananas",
  "Seven Davis Jr.",
  "Shash'U",
  "Sinister Dane",
  "Sinjin Hawke",
  "Sizarr",
  "Skepta",
  "Skrillex",
  "Sonny Digital",
  "Spank Rock",
  "Spiritual Friendship",
  "Superhero Killer",
  "Taso",
  "Thee Mike B",
  "The Martinez Brothers",
  "Tribe Icky",
  "Trooko",
  "Uniique",
  "Vin Sol & Matrixxman",
  "Westside Gunn",
  "Zebra Katz",
];
